server:
  port: 9090
  servlet:
    context-path: /api/v1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/syllabus
    username: postgres
    password: 123

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    locations: classpath://flyway
    baseline-on-migrate: true
    clean-on-validation-error: false

security:
  rsa:
    private-key: classpath:keys/private.pem
    public-key: classpath:keys/public.pem
  encoder:
    strength: 8
  token:
    prefix: Bearer
    client-ip: RequestGatewayControllerClientIp
    secret: $uper$3KR3T
    issuer: RequestGatewayController server
    audience: RequestGatewayController client
    access-expiration-time: 3600
    refresh-expiration-time: 604800
    jwt-token-header: Authorization
    token-cannot-be-verified: token cannot be verified
