server:
  port: 9090
  servlet:
    context-path: /api/v1

jwt:
  secret: apcsyllabus

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/syllabus
    username: postgres
    password: 123

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    locations: classpath://flyway
    baseline-on-migrate: true
    clean-on-validation-error: false
